# Generated by Django 4.1.2 on 2023-06-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_centertarkibi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.AddField(
            model_name='document',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
