# Generated by Django 4.1.2 on 2023-06-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_document_file_document_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=222)),
                ('name', models.CharField(max_length=222)),
                ('message', models.CharField(max_length=222)),
            ],
        ),
    ]
