# Generated by Django 4.1.2 on 2023-06-02 10:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maqola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.TextField()),
                ('title_en', models.TextField(null=True)),
                ('title_uz', models.TextField(null=True)),
                ('title_ru', models.TextField(null=True)),
                ('title_ky', models.TextField(null=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('content_en', ckeditor.fields.RichTextField(null=True)),
                ('content_uz', ckeditor.fields.RichTextField(null=True)),
                ('content_ru', ckeditor.fields.RichTextField(null=True)),
                ('content_ky', ckeditor.fields.RichTextField(null=True)),
            ],
        ),
    ]
