# Generated by Django 4.1.2 on 2023-06-06 05:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0002_maqola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailfunctions',
            name='sub_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailfunctions',
            name='sub_content_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailfunctions',
            name='sub_content_ky',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailfunctions',
            name='sub_content_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailfunctions',
            name='sub_content_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailfunctions',
            name='sub_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='detailfunctions',
            name='sub_title',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='detailfunctions',
            name='sub_title_en',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='detailfunctions',
            name='sub_title_ky',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='detailfunctions',
            name='sub_title_ru',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='detailfunctions',
            name='sub_title_uz',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
    ]
