# Generated by Django 4.1.2 on 2023-06-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0003_alter_detailfunctions_sub_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailfunctions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
